spring.application.name=sistur
spring.datasource.url=jdbc:postgresql://db.kwddavsummldocvmafgn.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=a4oTJLl4fUUzP2Dc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.br.gov.noronha.sistur=DEBUG
